export const ExplainerTexts = [
  {
    title: "What Is Boilerplate?",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Why Use Boilerplate?",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Build Content Library",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Write Grants",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Export Grants",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Customize Templates",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Track Fundraising",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Create Reports",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Boilerplate Team",
    text: "",
  },
];
