export const ExplainerTexts = [
  {
    title: "What Is Boilerplate?",
    text: "Boilerplate is based on our prior experience as grant writers. We have written grants for several smaller nonprofits, and we have noticed that they have fewer resources to dedicate to fundraising. Staff write grants in their spare time, on an ad hoc basis. They cannot organize materials, standardize their process, or track performance over time. If an experienced grant writer does contribute on a short-term or part-time basis, their work product is often not utilized after they leave. As a result, smaller nonprofits lose out on funding opportunities as well as long-term relationships with funding organizations. Boilerplate provides a simple, accessible solution. Users can build custom searchable libraries of content, then import them into grant templates where they can be revised into draft applications. Users can also store, review, and reuse grant applications, tracking successful applications over time. We also added features based on our own experience as grant writers, including word counts for each stored content block, section, and draft total. Boilerplate doesn't automate the application process. It provides a scaffold to support grantwriting so that nonprofits can use limited resources more effectively. We focused on smaller funding opportunities, since they're more accessible, easier to templatize, and often linked to annual and renewable grants. We are working to develop Boilerplate into a product, and we’ve just deployed the app in test. We’re working to refine our app based on user feedback. We're also building out our next release, including admin permissions, collaborative editing features like notes and comments, reports, and an export feature.",
  },
  {
    title: "Why Use Boilerplate?",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Build Content Library",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Write Grants",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Export Grants",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Customize Templates",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Track Fundraising",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Create Reports",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nunc feugiat risus laoreet, non tincidunt tortor imperdiet. Sed aliquam sollicitudin semper. Aliquam turpis ex, elementum id dolor et, dignissim pretium ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sagittis dolor ut bibendum scelerisque. Suspendisse id dolor sit amet lacus egestas venenatis. Proin velit leo, facilisis nec risus et, convallis pharetra nunc. Aliquam tristique fringilla ligula ac rutrum. Cras at tellus neque. In non libero dapibus, rutrum purus nec, pharetra metus. Donec dignissim nec eros nec molestie. Suspendisse potenti. Pellentesque accumsan tortor in pulvinar commodo. Proin a orci ac purus fringilla molestie sodales nec tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum magna et justo maximus semper. Morbi sodales, libero vitae placerat consectetur, neque dui imperdiet sapien, a dictum leo nulla id ante. Phasellus dapibus id magna ac feugiat.",
  },
  {
    title: "Boilerplate Team",
    text: "",
  },
];
